### ISSUE TITLE
Český účet

### ISSUE THREAD

**Issue by stehlikt** [slatinsky/php-pay-by-square#1]
Dobrý den,

chceme používat vaše řešení pro platbu skrze QR kód na našem webu, ale narazili jsme na problém. Když tam dáváme český iban a swift, tak bankovní aplikace hází chybu ( neznámý iban, i když iban existuje ), ale pokud tam zkusíme dát slovenksý iban, tak vše funguje v pořádku. Je možné, že aplikace přijímá pouze slovenské účty pro platbu v eurech ?

**Comment by slatinsky** [comment]
Dobrý deň,

keď už ste tento issue otvorili, dajte prosím feedback, či to aj s českými účtami bolo možné "spojadzniť".

Tento kód je v podstate "wrapper" nad riešením poskytnutým od [Jána Fečíka](https://jan.fecik.sk/blog/qr-generator-platieb-pay-by-square-v-php/), aby bolo jednoduché ho nasadiť.

**Comment by stehlikt** [comment]
Dobrý den,

kontaktoval jsem přímo pana Fečíka a bohužel není možné pro toto řešení používat české účty, jelikož Slovensko má jinou specifikaci pro pay by square, než Česko.

**Comment by slatinsky** [comment]
ďakujem za info, upravil som dokumentáciu
